name: Deploy to Production

on:
  push:
    branches: main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: placeholder
    - name: Adding known hosts
      run: ssh-keyscan -H ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts
    - name: Get old command json hash
      run: echo '::set-output name=HASH::ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} "cd qyf-bot && ~/.nvm/nvm-exec node scripts/hash-global-commands.js"'
      id: old-hash
    - name: Push files with rsync
      run: rsync -avzh --delete --exclude='/.git' --filter=':- .gitignore' ./ ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }}:/home/qyf/qyf-bot/
    - name: Setup and restart
      run: ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} "cd qyf-bot && ~/.nvm/nvm-exec npm run deploy"
    - name: Deploy new commands
      run: ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }} "cd qyf-bot && ~/.nvm/nvm-exec npm run commands:deploy-globals -- --hash ${{ steps.old-hash.HASH }}"
